### ISSUE TITLE
Specify Folder in Stream Only Configuration

### ISSUE THREAD

**Issue by kickmaleerie** [codeforbtv/StreamOnly#13]
Hi

I have the Stream Only plugin v0.2.1. installed on Omeka Classic 2.6.1 in a shared hosting environment with Infomaniak. The site uses the Berlin theme.

My Omeka root is /web/cms and URLs point to /cms e.g. _my_web_site__/cms/admin

By default when media files (images, video, audio ) are uploaded for an Item they are placed in /cms/files/original

In the Stream Only configuration there is the “Folder for Storing Audio Files” option and I am at a loss about how to define this. According to the docs the purpose of this is to prevent download of files from this directory.

For example if I create the folder /cms/files/sonly then how do I then reference this in the plugin configuration?

None of these work:

/cms/files/sonly
/files/sonly
/sonly

When the Input Type Metadata is set to “Stream Only” to use the plugin audio files are always placed in /cms/files/original and can of course be downloaded.

The plugin reports that it has been successfully configured whatever value is used.

Advice appreciated.

**Comment by kunikla** [comment]
Hi John,

Thanks for trying out the StreamOnly plugin!

Unfortunately, the version you have is nowhere near complete. As a 
member of the non-profit Code For Burlington 
<http://www.codeforbtv.org/>, I am developing this plugin for the 
non-profit Big Heavy World <https://bigheavyworld.com/> to enhance its 
Vermont Music Archive <https://omeka.bigheavyworld.com/> project (see 
project description 
<http://www.codeforbtv.org/projects/vt-audio-player>, which is mostly 
correct). Any description of what v0.2.1 of the StreamOnly plugin does 
is purely aspirational.

The most recent version of the code, 0.3.0, can be found in the Code For 
BTV repository <https://github.com/codeforbtv/StreamOnly>. You'll find 
better (but still aspirational) user documentation in the repository's 
Wiki <https://github.com/codeforbtv/StreamOnly/wiki>. You'll also see 
lots of Issues, and lots of TODO notes in the code. I am currently 
blocked on solving 2 problems:

 1. The current design makes it very difficult to know when the user
    overrides the Folder for Storing Audio Files option when editing an
    Item. One solution is a fairly large redesign. I am waiting for
    feedback from some senior developers. (See Issue #14
    <https://github.com/codeforbtv/StreamOnly/issues/14>)
 2. In order for the script that will fetch the audio file to execute,
    allowing the user of the website to play the audio, a Rewrite Rule
    needs to be added to to Omeka's .htaccess file. The code to update
    the .htaccess file during installation exists, but I haven't yet
    figured out what the rule should be. (See Issue #7
    <https://github.com/codeforbtv/StreamOnly/issues/7>)

I am very curious how you came to be interested in this plugin. I know 
from looking at the Omeka forums that there are people interested in 
using the capabilities of the StreamOnly plugin on their websites, and 
if you are one of them, I'd love to discuss with you what would make it 
a better plugin. If you're someone who collects Omeka plugins, I can let 
you know when there's a version that is worth collecting.

Kind regards,
Christina
